version: 2

build:
  os: ubuntu-lts-latest
  commands:
    - pip install -r requirements.txt  
    - make html  
    
sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.12
  install:
    - method: pip
      path: .
      extra_requirements:
        - all
    - requirements: docs/requirements_docs.txt

submodules:
  include: all