[global]
showWarningOnDirectExecution = false

[logger]
level = "info"

[client]
showErrorDetails = true

[server]
port = 8501
address = "localhost"
headless = false
enableCORS = false
enableXsrfProtection = false
folderWatchBlacklist = ['']
fileWatcherType = "auto"
cookieSecret = "foundation-design-aci318"
runOnSave = true
baseUrlPath = ""

[browser]
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"
